apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd/
  - vault/
  - longhorn/
  - couchdb/
  - cloudflared/cloudflared.yaml
  - prometheus/prometheus-app.yaml
  - vault-secrets-operator/
  - minio/
  - tailscale/
  - grafana/
  - harbor/app.yaml
